#pragma config(UART_Usage, UART1, uartUserControl, baudRate115200, IOPins, None, None)
#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    intakePot,      sensorPotentiometer)
#pragma config(Sensor, dgtl1,  rightQuad,      sensorQuadEncoder)
#pragma config(Sensor, dgtl6,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl12, liftStopButton, sensorTouch)
#pragma config(Sensor, I2C_1,  liftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           lidar,         tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           liftRO,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           liftLI,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveLFY,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           driveRB,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           driveLB,       tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           driveRFY,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           intakeY,       tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           liftLO,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          liftRI,        tmotorVex393_HBridge, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BCI_USE_AUTOTUNE
#include "..\..\BCI.h"

task main()
{
	clearDebugStream();

	//Arrays for our drive motors
	tMotor leftMotors[2] = {driveLFY, driveLB};
	tMotor rightMotors[2] = {driveRFY, driveRB};

	//Tune PID for 400 quadrature encoder ticks
	autotune_Run(leftMotors, 2, rightMotors, 2, leftQuad, rightQuad, 400);

  while(true) {EndTimeSlice();}
}
