#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BCI_USE_AUTOTUNE
#include "..\..\BCI.h"

task main()
{
	//Arrays for our drive motors
	tMotor leftMotors[2] = {leftMotor1, leftMotor2};
	tMotor rightMotors[2] = {rightMotor1, rightMotor2};

	//Tune PID for 400 quadrature encoder ticks
	autotune_Run(leftMotors, 2, rightMotors, 2, leftQuad, rightQuad, 400);
}
