#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port1,           leftDrive1,    tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftDrive2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightDrive1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightDrive2,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BCI_USE_PID_OPT //Tell BCI to include the PID_Optional extensions
#include "..\..\BCI.h"

task main()
{
  //Setup an array of our left and right drivetrain motors
  tMotor leftMotors[2] = {leftDrive1, leftDrive2};
  tMotor rightMotors[2] = {rightDrive1, rightDrive2};

  //Make two PID controllers for distance and angle
  //We don't control theirs sensors, so initialize them with NULL sensors
  pos_PID distancePID, anglePID;
  pos_PID_InitController(&distancePID, NULL, 0.3, 0.2, 0.1);
  pos_PID_InitController(&anglePID, NULL, 0.3, 0.2, 0.1);

  //Drive straight for 1000 ticks, output power to arrays leftMotors and
  //rightMotors of length 2, read from leftQuad and rightQuad, and use PID
  //controllers distancePID and anglePID
  PID_Opt_DriveStraight(1000, leftMotors, rightMotors, 2, leftQuad, rightQuad, &distancePID, &anglePID);
}
