#pragma config(Motor,  port2,           leftMotor	,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * This is a tuorial for how to use the basic features of motorControl. For
 * extra reference, see BCI\Modules\Core\motorControl.h
 */

//We will have two motors called leftMotor and rightMotor

#define BCI_USE_MOTORCONTROL
#include "..\..\BCI.h"

task main()
{
  //Tell the slew rate controller about leftMotor, using the default slew rate
  addMotor(leftMotor);

  //Tell the slew rate controller about rightMotor, using a custom slew rate
  addMotor(rightMotor, 1);

  //Start the slew rate controller
  startTask(motorSlewRateTask);

  //Tell the slew rate controller to slew leftMotor up to power 100
  setMotorSpeed(leftMotor, 100);

  //Force the slew rate controller to jump leftMotor down to power 10, skipping
  //the slewing process
  setMotorSpeed_Bypass(leftMotor, 10);

  //Read the current (requested) power of leftMotor
  getMotorSpeed(leftMotor);
}
