#pragma config(Sensor, dgtl7,  myQuad,  sensorQuadEncoder)
#pragma config(Motor,  port2,   myMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * This is a tuorial for how to use the basic features of positionPID. For
 * extra reference, see BCI\Modules\Core\positionPID.h
 */

//We will have a quadrature encoder for the PID controller to run off of and a
//motor to control the robot

#define BCI_USE_POS_PID
#include "..\..\BCI.h"

pos_PID myPID; //Make a pid controller

task main()
{
  //Initialize our pid controller with sensor myQuad and gains
  //kP = 1, kI = 2, and kD = 3
  pos_PID_InitController(&myPID, myQuad, 1, 2, 3);

  //Set the target position for our pid controller
  pos_PID_SetTargetPosition(&myPID, 100);

  //Run our motor with the output of the pid controller
  motor[myMotor] = pos_PID_StepController(&myPID);
}
