#pragma config(Sensor, dgtl1,  leftQuad,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  rightQuad,      sensorQuadEncoder)
#pragma config(Motor,  port2,           leftMotor1,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor2,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightMotor1,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           rightMotor2,   tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define BCI_USE_CUSTOM_TRUESPEED
#include "..\..\BCI.h"

task main()
{
  //Run our motor with the linearized value for our input (100 power)
  motor[leftMotor1] = BCI_GetTrueSpeed(100);

  //Setup arrays for our drive motors
  tMotor leftMotors[2] = {leftMotor1, leftMotor2};
  tMotor rightMotors[2] = {rightMotor1, rightMotor2};

  //Calculate our own truespeed LUT
  trueSpeed_Measure(leftMotors, 2, rightMotors, 2, leftQuad, rightQuad);
}
