#pragma config(Sensor, dgtl7,  myQuad,  sensorQuadEncoder)
#pragma config(Motor,  port2,   myMotor, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * This is a tuorial for how to use the basic features of velocityTBH. For
 * extra reference, see BCI\Modules\Core\velocityTBH.h
 */

//We will have a quadrature encoder for the TBH controller to run off of and a
//motor to control the robot

#define BCI_USE_VEL_TBH
#include "..\..\BCI.h"

vel_TBH myTBH; //Make a tbh controller

task main()
{
  //Initialize our tbh controller with sensor myQuad and gains
  //gain = 1, approximate controller output at zero error = 80
  vel_TBH_InitController(&myTBH, myQuad, 1, 80);

  //Set the target velocity for our tbh controller
  vel_TBH_SetTargetVelocity(&myTBH, 10);

  //Run our motor with the output of the tbh controller
  motor[myMotor] = vel_TBH_StepController(&myTBH);
}
